spec:
  replicas: 2
  template:
    spec:
      containers:
      - env:
        - name: OPENSHIFT_API_URL
          value: ${OPENSHIFT_API_URL}
        - name: KEYCLOAK_SAAS_URL
          value: ${KEYCLOAK_SAAS_URL}
        - name: WIT_URL
          value: ${WIT_URL}
        - name: AUTH_URL
          value: ${AUTH_URL}
        - name: LAUNCHPAD_BACKEND_CATALOG_GIT_REF
          value: v15
        workingDir: /home
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "forge/version"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 120
          failureThreshold: 10
          httpGet:
            path: "forge/version"
            port: 8080
      serviceAccountName: "${project.artifactId}"
